ARM: configs: lineage_*: enable flags for QTAGUID
This is required for google apps to work. If not, bandwidth controls will be disabled.

020-12-01 20:00:42.339 14283-14283/system_process E/SystemServer: BOOT FAILURE making Network Policy Service ready
    java.lang.IllegalStateException: Service NetworkPolicy init timeout
        at com.android.server.net.NetworkPolicyManagerService.systemReady(NetworkPolicyManagerService.java:887)
        at com.android.server.SystemServer.lambda$startOtherServices$4(SystemServer.java:1890)
        at com.android.server.-$$Lambda$SystemServer$s9erd2iGXiS7bbg_mQJUxyVboQM.run(Unknown Source:53)
        at com.android.server.am.ActivityManagerService.systemReady(ActivityManagerService.java:15437)
        at com.android.server.SystemServer.startOtherServices(SystemServer.java:1810)
        at com.android.server.SystemServer.run(SystemServer.java:453)
        at com.android.server.SystemServer.main(SystemServer.java:302)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:491)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:838)

Change-Id: I8cdc8de3982b7593087f38090774e2597a4975a1